### ISSUE TITLE
lodash.template critical vulnerabilities from Mend

### ISSUE THREAD

**Issue by tech-run** [stephenlacy/gulp-git#204]
Mend Identified the following vulnerablities in lodash.template which requires an upgrade and has been identified within this repo. 

Library | Description | Top Fix
-- | -- | --
lodash.template-3.6.2.tgz | Versions of lodash lower than 4.17.12 are vulnerable to Prototype Pollution. The function defaultsDeep could be tricked into adding or modifying properties of Object.prototype using a constructor payload. | Upgrade to version lodash-4.17.12, lodash-amd-4.17.12, lodash-es-4.17.12, lodash.defaultsdeep-4.6.1, lodash.merge 4.6.2, lodash.mergewith-4.6.2, lodash.template-4.5.0-Message: Upgrade to versionDetails: https://github.com/advisories/GHSA-jf85-cpcp-j695

**Comment by stephenlacy** [comment]
Closed with #206
